@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.bytelaw.common.integration;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;