modLoader="javafml"
loaderVersion="[35,)"
license="MIT License"
issueTrackerURL="https://github.com/ByteLaw5/ColorableBooks/issues"
[[mods]]
modId="colorablebooks"
version="0.1A"
displayName="Colorable Books"
updateJSONURL="https://raw.githubusercontent.com/ByteLaw5/ColorableBooks/main/updatechecker.json"
logoFile="logo.png"
credits=""
authors="ByteLaw"
description='''This mod allows you to use minecraft color codes in your book and quills!
'''
[[dependencies.colorablebooks]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.colorablebooks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
